import "./globals.css";
import { Montserrat, Tangerine } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/footer/Footer";

export const montserrat = Montserrat({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
});
export const tangerine = Tangerine({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-tangerine",
  display: "swap",
});
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${montserrat.variable} ${tangerine.variable} text-black antialiased`}
      >
        <StoreProvider>

          <Header />
          <main className="flex-1">{children}</main>

          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
