import "./globals.css";
import { Geist, Montserrat } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Header from "@/components/layout/Header/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${montserrat.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
