import "./globals.css";
import { Montserrat, Tangerine } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Header from "@/components/layout/Header/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
});
const tangerine = Tangerine({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-tangerine",
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${tangerine.variable} text-black antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
